--- Unit tests for the difft JSON -> Region parser (spec §11 step 1).
---
--- These run the REAL fixtures captured from Difftastic 0.69.0 (see
--- tests/fixtures/*.json, generated by the difft binary, not hand-written) so
--- the parser is validated against ground truth, not against the spec's prose
--- (which got the line-number base wrong).
---
--- Run with:
---   nvim --headless -u tests/minimal_init.lua \
---     -c "PlenaryBustedDirectory tests/ { minimal_init = 'tests/minimal_init.lua' }"

local core = require("dft-signs.core")

local function read_fixture(name)
  local path = "tests/fixtures/" .. name
  local fd = assert(io.open(path, "r"), "missing fixture: " .. path)
  local data = fd:read("*a")
  fd:close()
  return vim.json.decode(data)
end

describe("core.parse", function()
  it("short-circuits an unchanged file", function()
    local result = core.parse(read_fixture("unchanged.json"))
    assert.are.equal("unchanged", result.status)
    assert.are.same({}, result.regions)
  end)

  it("emits a whole-buffer add region for a created file", function()
    local result = core.parse(read_fixture("created.json"))
    assert.are.equal("created", result.status)
    assert.are.equal(1, #result.regions)
    assert.are.equal("add", result.regions[1].kind)
    assert.are.equal(1, result.regions[1].span.from)
    assert.are.equal(-1, result.regions[1].span.to) -- sentinel: to end of buffer
  end)

  it("emits a delete region for a deleted file", function()
    local result = core.parse(read_fixture("deleted.json"))
    assert.are.equal("deleted", result.status)
    assert.are.equal(1, #result.regions)
    assert.are.equal("delete", result.regions[1].kind)
    assert.are.equal(1, #result.regions[1].deletions)
  end)

  it("normalizes 0-based line numbers to 1-based for a changed file", function()
    -- changed.json diffs old.rs -> new.rs where new.rs adds `let y = 3;` as the
    -- new buffer line 3 (0-based line_number 2), and mutates 1 -> 2 on line 2.
    local result = core.parse(read_fixture("changed.json"))
    assert.are.equal("changed", result.status)
    assert.is_true(#result.regions >= 1)

    -- Collect every changed buffer line across all regions.
    local changed = {}
    for _, region in ipairs(result.regions) do
      for _, line in ipairs(region.changed) do
        changed[line] = true
      end
    end

    -- 0-based line_number 1 (the `let x = 1` -> `let x = 2` line) becomes
    -- 1-based buffer line 2. The added line (0-based 2) becomes buffer line 3.
    assert.is_true(changed[2], "expected buffer line 2 to be changed")
    assert.is_true(changed[3], "expected buffer line 3 to be changed")
    -- Line 1 (`fn main() {`) is unchanged and must NOT be flagged. This is the
    -- whole structural point: no false positives on untouched lines.
    assert.is_nil(changed[1])
  end)

  it("treats lhs-only lines as deletions, not changes", function()
    -- deletion.json removes `let b = 2;` and `let c = 3;` (both lhs-only).
    local result = core.parse(read_fixture("deletion.json"))
    assert.are.equal("changed", result.status)

    local total_deletions = 0
    local changed_count = 0
    for _, region in ipairs(result.regions) do
      for _, d in ipairs(region.deletions) do
        total_deletions = total_deletions + d.count
      end
      changed_count = changed_count + #region.changed
    end

    -- Two lines were deleted and nothing on the buffer side actually changed.
    assert.are.equal(2, total_deletions)
    assert.are.equal(0, changed_count)
  end)

  it("captures token-level edits for the span preview", function()
    -- changed.json mutates `1` -> `2` and adds `let y = 3;`. The edits array
    -- must retain the actual token content on both sides so the preview can
    -- show what really changed rather than faking a line block.
    local result = core.parse(read_fixture("changed.json"))

    local all = {}
    local has_lhs, has_rhs = false, false
    for _, region in ipairs(result.regions) do
      assert.is_table(region.edits)
      for _, e in ipairs(region.edits) do
        assert.is_true(e.side == "lhs" or e.side == "rhs")
        assert.is_number(e.line)
        assert.is_string(e.content)
        assert.is_string(e.highlight)
        all[e.content] = true
        if e.side == "lhs" then has_lhs = true end
        if e.side == "rhs" then has_rhs = true end
      end
    end

    -- Both the reference token `1` and the new tokens (`2`, `y`) must appear.
    assert.is_true(all["1"], "expected reference token '1' in edits")
    assert.is_true(all["2"], "expected new token '2' in edits")
    assert.is_true(all["y"], "expected added token 'y' in edits")
    assert.is_true(has_lhs, "expected at least one lhs edit")
    assert.is_true(has_rhs, "expected at least one rhs edit")
  end)

  it("produces a valid span covering the changed buffer lines", function()
    local result = core.parse(read_fixture("changed.json"))
    for _, region in ipairs(result.regions) do
      assert.is_true(region.span.from >= 1)
      assert.is_true(region.span.to >= region.span.from)
      -- Every changed line must fall inside the span (layer 1 ⊆ layer 2).
      for _, line in ipairs(region.changed) do
        assert.is_true(line >= region.span.from and line <= region.span.to)
      end
    end
  end)

  it("does not crash on a malformed / empty object", function()
    local result = core.parse({})
    assert.are.equal("unchanged", result.status)
    assert.are.same({}, result.regions)

    local drift = core.parse({ status = "changed" }) -- no chunks key
    assert.are.same({}, drift.regions)
  end)

  it("flags text-language fallback", function()
    local result = core.parse({ language = "Text", status = "unchanged" })
    assert.is_true(result.fallback)
  end)
end)
